default: &default
#  adapter: mysql2
  adapter: postgres
  encoding: utf8
  pool: 5
  username: root
  password: altius@123

development:
  <<: *default
  database: vpcvi-u2

production:
  <<: *default
  database: vpcvi-u2

